### ISSUE TITLE
[Question] When would you recommend using OptSpace or rclr over clr? 

### ISSUE THREAD

**Issue by jolespin** [cjm007/DEICODE#10]
Very interesting method!  I look forward to using this on some of my count tables:
```python
from deicode.optspace import OptSpace
from deicode.preprocessing import rclr
```
I usually use `clr` or `ilr`.  When would you recommend using `OptSpace` or `rclr` over regular `clr`?

**Comment by cameronmartino** [comment]
rclr and OptSpace are used to perform SVD (aka PCA) on compositional data with missing values, without the use of pseudo counts. So rclr & OptSpace may be used over clr/ilr (with pseudo counts) & PCA, if there are any missing values in the dataset (usually converted to zeros). 

Thanks and I hope it helps to find something cool in your dataset!

**Comment by jolespin** [comment]
Interesting!  Yea, I have a lot of counts data in the form of transcript expression and marker gene counts (i.e., 16S OTU centroids).  Are the dimensions still preserved with `rclr` as `clr` is from `skbio` (in comparison to `ilr` or using `OptSpace/PCA` and projecting it into the original dimension space)? 

My understanding of usage is as follows (please correct me if I'm wrong): 

(1) `OptSpace` can be used as a drop in replacement for `sklearn's PCA` where missing values are handled appropriately; and 
(2) `rclr` can be used like `clr` without using pseudo counts

That would be awesome to incorporate this in my analysis (with citations of course).

**Comment by cameronmartino** [comment]
Yes, both `rclr` and  clr preserves the original dimensions and both can be easily inverse transformed with skbio’s `clr_inv`. 

(1) Yes exactly, one way to think of [OptSpace](https://arxiv.org/pdf/0906.2027.pdf) (in this interpretation) is an SVD that relies on only the known values of the dataset. In this case that dataset is compositional (i.e. `rclr`) which is an approximation of the `clr` using the known data. 

(2) Yes, with the exception that `rclr` will have nan values in the transformed dataset where missing or zero values we’re located in the original dataset. The `clr` transformation with pseudo count should not contain any `nans` (or `infs`). 

That would be great, I see you are local. If you would like an in person demo on your data feel free to stop by the lab (Knight lab, UCSD).
