### ISSUE TITLE
broken image links in tutorial

### ISSUE THREAD

**Issue by mestaki** [cjm007/DEICODE#24]
Hey folks,
Just trying to go through the tutorial and noticed that the first two images appear to be broken.

**Comment by cameronmartino** [comment]
@mestaki  Thanks for bringing this to my attention. I will fix the links now. For the time being, the tutorial is also available [here](https://forum.qiime2.org/t/robust-aitchison-pca-beta-diversity-with-deicode/8333) or [here](https://library.qiime2.org/plugins/deicode/19/). Thanks again!
