### ISSUE TITLE
proportion explained / eigenvalues are swapped

### ISSUE THREAD

**Issue by mortonjt** [cjm007/DEICODE#32]
It looks like either the eigenvalues or the proportion explained are flipped
Below is an example from an ordination results object

![image](https://user-images.githubusercontent.com/4184797/56171780-77ca2800-5fb4-11e9-922f-34678e7ba33e.png)

**Comment by cameronmartino** [comment]
@mortonjt  It looks to me that the Eigvals are reversed. Putting in a PR now to fix this.

**Comment by cameronmartino** [comment]
Closing this issue, it is solved in PR #33 and PR #34.
