### ISSUE TITLE
The centering issue remains

### ISSUE THREAD

**Issue by mortonjt** [cjm007/DEICODE#37]
I don't think #26 has been completely fixed.

Below are some examples from the CF dataset: https://qiita.ucsd.edu/study/description/10863

![image](https://user-images.githubusercontent.com/4184797/60449163-097d2500-9bf5-11e9-818b-705464486e58.png)

![image](https://user-images.githubusercontent.com/4184797/60449175-0da94280-9bf5-11e9-85e9-1dfd189faee2.png)

Below are the commands / files used to reproduce these figures (in qiime2-2019.4).
```
deicode --in-biom filtered_otus_nt.biom --output-dir deicode_microbes --rank 3 --iterations 10
qiime tools import --input-path deicode_microbes/ordination.txt --output-path ordination.qza --type "PCoAResults % Properties('biplot')"
qiime emperor biplot --i-biplot ordination.qza --m-sample-metadata-file sample-metadata.txt --output-dir emperor-microbes

deicode --in-biom filtered_otus_nt.biom --output-dir deicode_metabolites --rank 3 --iterations 10
qiime tools import --input-path deicode_metabolites/ordination.txt --output-path ordination.qza --type "PCoAResults % Properties('biplot')"
qiime emperor biplot --i-biplot ordination.qza --m-sample-metadata-file sample-metadata.txt --output-dir emperor-metabolites
```

[Archive.zip](https://github.com/biocore/DEICODE/files/3346390/Archive.zip)

What is happening - If I had to guess, it probably has to do with the centering operation we had previously.  If we have a rank=3 decomposition, it'll actually project the loadings into a 2D space (as noted in the above visualizations).  Centering the loading matrices doesn't necessarily mean that the matrix itself is centered.  There is probably a way to do this on the load matrices directly - but I can't think, of this off the top of my head.

The short term solution would be center the full estimated matrix as follows

```python
from scipy.sparse.linalg import svds
X = opt.sample_weights @ opt.s @ opt.feature_weights.T
X = X - X.mean(axis=0)
X = X - X.mean(axis=1).reshape(-1, 1)
u, s, v = svds(X, k=rank)
feature_loading = pd.DataFrame(v.T, index=table.columns, columns=rename_cols)
sample_loading = pd.DataFrame(u, index=table.index, columns=rename_cols)
```

This is _not_ optimal, since it performs a redundant svd operation.  But at least it'll lead to more correct biplots.

I should be able to push in a PR in about 2 weeks.  This time, we will want to have clear cut unittests and visualizations (and maybe even an emperor mchelper, CC @ElDeveloper ).

**Comment by cameronmartino** [comment]
I think PR #36 may have already solved this issue. When I run the commands on the data you attched 
```shell
# microbes
deicode --in-biom filtered_otus_nt.biom --output-dir deicode_microbes --n_components 3 --max_iterations 10
qiime tools import --input-path deicode_microbes/ordination.txt --output-path ordination.qza --type "PCoAResults % Properties('biplot')"
qiime emperor biplot --i-biplot ordination.qza --m-sample-metadata-file sample-metadata.txt --output-dir emperor-microbes
# metabolites
deicode --in-biom filtered_lcms_nt.biom --output-dir deicode_metabolites --n_components 3 --max_iterations 10
qiime tools import --input-path deicode_metabolites/ordination.txt --output-path ordination.qza --type "PCoAResults % Properties('biplot')"
qiime emperor biplot --i-biplot ordination.qza --m-sample-metadata-file sample-metadata.txt --output-dir emperor-metabolites
```
I get the following plots:

### microbes
![emperor_microbes](https://user-images.githubusercontent.com/15164295/60451867-f1e87100-9be1-11e9-9333-63f726080625.png)
### metabolites
![emperor_metabolites](https://user-images.githubusercontent.com/15164295/60451870-f3b23480-9be1-11e9-9101-35895cb494a9.png)

Regardless a double check of centering may be a good idea. Possibly we could center inside of the gradient descent by adding ...

```python
def center(X):
    X = X - X.mean(axis=0)
    X = X - X.mean(axis=1).reshape(-1, 1)
    return X
```
```python
imputed = center(imputed)
obs  = center(obs)
```
to this function in between line _256_ and _257_:

https://github.com/biocore/DEICODE/blob/b1145a7d45747e84a162984f621c09e0c7a1d87b/deicode/optspace.py#L237-L265

This would prevent the double SVD. What do you think?

**Comment by mortonjt** [comment]
oh awesome!  I did not see that PR.  Let me take a look at that.

**Comment by mortonjt** [comment]
ok, it doesn't look fixed on my machine -- there is still a 2D plane here for the metabolites.

![image](https://user-images.githubusercontent.com/4184797/60454504-f4f35980-9c01-11e9-935e-ef6ec9dc46e2.png)
