### ISSUE TITLE
pip install  and setup.py doesn't install DEICODE on computing cluster

### ISSUE THREAD

**Issue by Jigyasa3** [cjm007/DEICODE#48]
I tried both methods for DEICODE installation- (conda installation breaks on the computing cluster, so I cannot use conda install)

1. Installation of deicode directly from pip gives the following error-
$module load qiime2/2019.1
$module load python/3.5.2
$pip3 install --user deicode

Error-
 error: command 'g++' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cvxpy

 ----------------------------------------
  Failed building wheel for scs
Command "/apps/free72/python/3.5.2/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/scratch/pip-build-g0r_6fzj/scs/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /scratch/pip-pnz95s96-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /scratch/pip-build-g0r_6fzj/scs/

NOTE- I am using gcc/4.9.2. I tried with previous versions too, they give the same error.

2. I tried installing from source code- 
$wget https://github.com/biocore/DEICODE/archive/1.3.0.tar.gz
$tar -xvzf 1.3.0.tar.gz
$cd DEICODE
$python3 setup.py install --user

Error-
Processing` dependencies for DEICODE==1.3.0

error: scikit-learn 0.18.1 is installed but scikit-learn>=0.21.2 is required by `{'fancyimpute'}

NOTE-But I have scikit-learn version 0.21.3. Then why am I getting this error?

**Comment by mortonjt** [comment]
Which python are you using? What does `which python` or `which pip3`
return? Are you using a virtualenv?

Also, conda should be fine on the cluster. Feel free to post those errors
as well.

**Comment by cameronmartino** [comment]
I updated the GitHub releases, they were very outdated, thus your error in (2). But that will not solve your overall problem as @mortonjt  pointed out. The pip version you tried to install in (1) will have no difference from this repo (except some minor doc fixes see PR #44).

**Comment by Jigyasa3** [comment]
thank you @cameronmartino! It's working now. My pip was broken. Thank you!

**Comment by cameronmartino** [comment]
Great, I’m glad it worked out.
