### ISSUE TITLE
 (1/1) Invalid value for '--i-table': 'kelp-biom.qza' is not a   QIIME 2 Artifact (.qza)

### ISSUE THREAD

**Issue by scleractinia** [cjm007/DEICODE#66]
Hi All,

I generated my biom table with qiime version (qiime2-amplicon-2023.9), and then launched qiime2-2020.6 to run deicode, and I am encountering this error:  (1/1) Invalid value for '--i-table': 'kelp-biom.qza' is not a   QIIME 2 Artifact (.qza)

I am guessing it's version incompatibilities, but am unsure of how to get around this without running the whole pipeline through the older version again. 

Attached is my table that I am trying to run deicode with. 
[kelp-deblur-sepp-gg-only-noUnassigned-noEukaryota-noMito-noChlor-noDbltns-onlyKelp-min1500-biom.qza.zip](https://github.com/biocore/DEICODE/files/14500622/kelp-deblur-sepp-gg-only-noUnassigned-noEukaryota-noMito-noChlor-noDbltns-onlyKelp-min1500-biom.qza.zip)

**Comment by cameronmartino** [comment]
Hi @scleractinia,

Thanks for reaching out. Please use [Gemelli](https://github.com/biocore/gemelli)'s RPCA function, it should solve the problem.

Thanks,

Cameron
